#!/usr/bin/env python3

# Autogenerated with DRAKON Editor 1.8

def main():
        #item 28
    _sw_28 = x = 0
    if  (x < 0):
        #item 13
        print 'Negative changed to zero'
        x=x+1
        print x
        return None
    elif (x>0):
        #item 14
        print 'x>0' 
        x=x-1
        print x
        return None
    elif (x==0):
        #item 15
        print 'Zero'
        return None
    else:
        raise Exception("Not expected:  " + str(_sw_28))
    

main()
