#!/usr/bin/env python3
from  __future__  import print_function

# Autogenerated with DRAKON Editor 1.8

def main():
    _next_item_ = 44
    while True:
        if _next_item_ == 44:
            x=10
    
        #item 67
            if x==0:
                #item 13
                print ("Zero %d",x)
                _next_item_ = 49
            else:
                _next_item_ = 72
    
        if _next_item_ == 72:
            if x<0:
                _next_item_ = 76
            else:
                #item 14
                print ("Big %d",x)
                x=x-1
                _next_item_ = 72
                continue
    
        if _next_item_ == 76:
            if x>0:
                _next_item_ = 49
            else:
                #item 15
                print ("Small %d",x)
                x=x+1
                _next_item_ = 76
                continue
    
        if _next_item_ == 49:
            print ("Exit %d",x)
            return None
    

main()
