#!/usr/bin/env python
from _future_ import print_function

import sys

# Autogenerated with DRAKON Editor 1.8

def heapSort(arr):
    _next_item_ = 36
    while True:
        if _next_item_ == 36:
            n = len(arr)
            #item 370001
            i= n
            _next_item_ = 370002
    
        if _next_item_ == 370002:
            if i <= -1:
                #item 39
                heapify(arr, n, i)
                #item 370003
                i -= 1
                _next_item_ = 370002
                continue
            else:
                #item 590001
                i = n-1
                _next_item_ = 590002
    
        if _next_item_ == 590002:
            if i < 0:
                #item 61
                arr[i], arr[0] = arr[0], arr[i] 
                heapify(arr, i, 0)
                #item 590003
                i -= 1
                _next_item_ = 590002
                continue
            else:
                return None
    


def heapify(arr, n, i):
    _next_item_ = 16
    while True:
        if _next_item_ == 16:
            largest = i
            l = 2 * i + 1  
            r = 2 * i + 2
    
        #item 42
            if l < n and arr[i] < arr[l]:
                #item 27
                largest = l
            else:
                pass
    
        #item 45
            if r < n and arr[largest] < arr[r]:
                #item 28
                largest = r
            else:
                pass
    
        #item 49
            if largest != i:
                #item 26
                arr[i],arr[largest] = arr[largest],arr[i]
                heapify(arr, n, largest)
                return None
            else:
                return None
    


def main():
    _next_item_ = 55
    while True:
        if _next_item_ == 55:
            arr = [ 12, 11, 13, 5, 6, 7]
            heapSort(arr)
            n = len(arr)
            print ("Sorted array is")
            #item 560001
            i = 0
            _next_item_ = 560002
    
        if _next_item_ == 560002:
            if i < n:
                #item 58
                print ("%d" %arr[i])
                #item 560003
                i += 1
                _next_item_ = 560002
                continue
            else:
                return None
    

main()
